import type { Metadata } from "next";
import "./globals.css";
import { Vazirmatn } from "next/font/google";
import localFont from "next/font/local";
import ThemeProvider from "@/components/ThemeProvider";

const vazir = Vazirmatn({
  subsets: ["arabic", "latin"],
  display: "swap",
  variable: "--font-vazir",
});

const iranSans = localFont({
  src: "/AIranianSans.woff2",
  display: "swap",
  variable: "--font-iranSans-local",
});

export const metadata: Metadata = {
  title: "Azura Dashboard",
  description: "Generated by zizi and amir",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa-IR"
      dir="rtl"
      className={`${iranSans.variable} ${vazir.variable}`}
    >
      <body className="w-full h-screen">
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
